title: ThingsBoard
name: ThingsBoard
author: thingsboard
logo: https://img.thingsboard.io/thingsboard_logo.png
url: https://thingsboard.io

twitter:
  username: thingsboard

social:
  name: ThingsBoard
  links:
    - https://twitter.com/thingsboard
    - https://github.com/thingsboard/thingsboard
    - https://www.facebook.com/thingsboard
    - https://www.youtube.com/channel/thingsboard

seo:
  type: WebSite

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  html_to_native: true
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
baseurl:
incremental: true

exclude:
  - .idea

safe: false
lsi: false

sass:
  style: compressed

defaults:
  -
    scope:
      path: ""
    values:
      image:
        path: https://img.thingsboard.io/thingsboard_logo.png
        twitter: https://img.thingsboard.io/thingsboard_logo.png
        facebook: https://img.thingsboard.io/thingsboard_logo.png
      version: "v1.0"
      githubbranch: "master"
      docsbranch: "master"
  -
    scope:
      path: docs
    values:
      layout: docwithnav
      showedit: true

permalink: pretty

plugins:
  - jekyll-redirect-from
  - jekyll-seo-tag

collections:
  careers:
    output: true

release:
  branch: release-3.9
  branch_major_next: master
  ver: 3.9
  ce_ver: 3.9
  ce_tag: v3.9
  ce_full_ver: 3.9.0
  pe_ver: 3.9pe
  pe_full_ver: 3.9.0PE
  wd_examples_commit: v3.9
  # >>> EDGE
  edge_ver: 3.9
  edge_tag: v3.9
  edge_full_ver: 3.9.0EDGE
  pe_edge_ver: 3.9pe
  pe_edge_full_ver: 3.9.0EDGEPE
  # <<< EDGE
  ce_flutter_app_ver: 1.4.0
  pe_flutter_app_ver: 1.4.0
  broker_full_ver: 2.0.1
  broker_branch: release-2.0.1
  trendz_ver: 1.12.0
